// SPDX-License-Identifier: MIT

package io.github.northmaxdev.coinplot.backend.core.exchange;

import io.github.northmaxdev.coinplot.backend.core.currency.Currency;
import io.github.northmaxdev.coinplot.lang.Strings;
import io.github.northmaxdev.coinplot.lang.chrono.LocalDateInterval;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

import static java.util.stream.Collectors.joining;

public final class ExchangeRateSetRequests {

    public static final class ParametersBuilder {

        private static final String STANDARD_TARGET_DELIMITER = ",";

        private final @Nonnull ExchangeRateSetRequest request;
        private @Nullable String baseParameterName;
        private @Nullable String targetsParameterName;
        private @Nullable String startParameterName;
        private @Nullable String endParameterName;
        private @Nonnull DateTimeFormatter dateFormatter;

        public ParametersBuilder(@Nonnull ExchangeRateSetRequest request) {
            this.request = Objects.requireNonNull(request, "request is null");
            this.baseParameterName = null;
            this.targetsParameterName = null;
            this.startParameterName = null;
            this.endParameterName = null;
            this.dateFormatter = DateTimeFormatter.ISO_LOCAL_DATE;
        }

        public ParametersBuilder baseName(@Nullable String parameterName) {
            this.baseParameterName = parameterName;
            return this;
        }

        public ParametersBuilder targetsName(@Nullable String parameterName) {
            this.targetsParameterName = parameterName;
            return this;
        }

        public ParametersBuilder startName(@Nullable String parameterName) {
            this.startParameterName = parameterName;
            return this;
        }

        public ParametersBuilder endName(@Nullable String parameterName) {
            this.endParameterName = parameterName;
            return this;
        }

        public ParametersBuilder dateFormatter(@Nonnull DateTimeFormatter formatter) {
            this.dateFormatter = Objects.requireNonNull(formatter, "formatter is null");
            return this;
        }

        public Map<String, String> build() {
            Map<String, String> parameters = new HashMap<>(4);

            if (baseParameterName != null) {
                request.getBase()
                        .map(Currency::getCode)
                        .ifPresent(currencyCode -> parameters.put(baseParameterName, currencyCode));
            }

            if (targetsParameterName != null) {
                Optional<String> joinedTargetCodes = joinTargetCodes();
                joinedTargetCodes.ifPresent(s -> parameters.put(targetsParameterName, s));
            }

            LocalDateInterval dateInterval = request.getDateInterval();

            if (startParameterName != null) {
                LocalDate start = dateInterval.start();
                parameters.put(startParameterName, dateFormatter.format(start));
            }

            if (endParameterName != null) {
                LocalDate end = dateInterval.end();
                parameters.put(endParameterName, dateFormatter.format(end));
            }

            return parameters;
        }

        private Optional<String> joinTargetCodes() {
            String s = request.getTargets()
                    .stream()
                    .filter(Objects::nonNull) // Just in case
                    .map(Currency::getCode)
                    .collect(joining(STANDARD_TARGET_DELIMITER));

            return Strings.emptyToOptional(s);
        }

        @Override
        public boolean equals(Object obj) {
            return obj instanceof ParametersBuilder that
                    && Objects.equals(this.request, that.request)
                    && Objects.equals(this.baseParameterName, that.baseParameterName)
                    && Objects.equals(this.targetsParameterName, that.targetsParameterName)
                    && Objects.equals(this.startParameterName, that.startParameterName)
                    && Objects.equals(this.endParameterName, that.endParameterName)
                    && Objects.equals(this.dateFormatter, that.dateFormatter);
        }

        @Override
        public int hashCode() {
            return Objects.hash(
                    request,
                    baseParameterName,
                    targetsParameterName,
                    startParameterName,
                    endParameterName,
                    dateFormatter
            );
        }

        @Override
        public @Nonnull String toString() {
            // Generated by IntelliJ IDEA 2023.2
            return "ParametersBuilder{" +
                    "request=" + request +
                    ", baseParameterName='" + baseParameterName + '\'' +
                    ", targetsParameterName='" + targetsParameterName + '\'' +
                    ", startParameterName='" + startParameterName + '\'' +
                    ", endParameterName='" + endParameterName + '\'' +
                    ", dateFormatter=" + dateFormatter +
                    '}';
        }
    }

    private ExchangeRateSetRequests() {
        throw new UnsupportedOperationException();
    }

    public static boolean basicPropertiesAreEqual(
            @Nonnull ExchangeRateSetRequest a,
            @Nonnull ExchangeRateSetRequest b) {
        Objects.requireNonNull(a, "a is null");
        Objects.requireNonNull(b, "b is null");
        return Objects.equals(a.getBase(), b.getBase())
                && Objects.equals(a.getTargets(), b.getTargets())
                && Objects.equals(a.getDateInterval(), b.getDateInterval());
    }

    public static int hashBasicProperties(@Nonnull ExchangeRateSetRequest request) {
        Objects.requireNonNull(request, "request is null");
        return Objects.hash(request.getBase(), request.getTargets(), request.getDateInterval());
    }
}
